services:
  angular-app:
    container_name: angular-app
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4201"
    command: sh -c "ng serve"
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app

